<template>
  <div>
    <div v-for="part in level">
      <div>({{part.Name}} {{part.PlaceName}}) {{part.CharName}}：{{part.Words}}</div>
    </div>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        level: [
          {
            "ID": 501050,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 501051,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "格尼尔",
            "CharImageID": 3,
            "Position": 1,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_039_05",
            "Words": "女神在上，这棵树也太巨大了吧……要不是之前在空中被迷雾所遮盖，完全不可能忽略它的存在啊。",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkEffectGroup1": [
              5010011,
              5010012
            ],
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501051,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 501052,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "艾梅达",
            "CharImageID": 4,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_038_09",
            "Words": "从它散发出的魔法能量来说，这应该就是兰迪乌斯和西格玛他们所说的「世界之树」没错了。",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501052,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 501053,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 1,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_037_10",
            "Words": "「世界之树」，伊雷斯大陆上竟然散布着生命力强大如斯的存在吗……真是令人惊叹。",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501053,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 501054,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "格尼尔",
            "CharImageID": 3,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_039_05",
            "Words": "唔，太过沉迷于感叹可不行……我们到这里的任务是来追逐那颗倒霉的红色流星的！",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkEffectGroup1": [
              5010011,
              5010012
            ],
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501054,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 501055,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "格尼尔",
            "CharImageID": 3,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_039_05",
            "Words": "如果之前安杰丽卡的观测没错的话，应该是离这颗世界树还有一段距离。",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkEffectGroup1": [
              5010011,
              5010012
            ],
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501055,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 501056,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 1,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_037_10",
            "Words": "是啊，我们应该尽快赶去那个坠落点……",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501056,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 501057,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 1,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_037_10",
            "Words": "等等、是什么人在那儿——！？",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501057,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 501058,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "克利姆索骑士",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_037_10",
            "Words": "……被发现了么，过人的观察力……是个强者。",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501058,
            "Name": "第二部第2章战外前置",
            "NextDialogID": 0,
            "FrameType": 0,
            "PlaceName": "世界树下",
            "CharName": "克利姆索骑士",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/6_ABS/BG63/BG63.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S21_037_10",
            "Words": "那么……是要先返回报告、还是纵情一战呢？",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501060,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501061,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "安杰丽卡",
            "CharImageID": 213,
            "Position": 1,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "StoryS05_045_03",
            "Words": "摩西摩西……这里是已经抵达伊雷斯的安杰丽卡。杰西卡老师，收到请回话！",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501061,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501062,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "杰西卡",
            "CharImageID": 22,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S08_030_02",
            "Words": "太好了！我一直在等待你们的讯息，情况如何？",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501062,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501063,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "安杰丽卡",
            "CharImageID": 213,
            "Position": 1,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "StoryS05_045_03",
            "Words": "马修他们正在向陨星的落点靠近中，除了遇到一些奇怪的敌人以外一切正常。",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501063,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501064,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "杰西卡",
            "CharImageID": 22,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S08_030_02",
            "Words": "「奇怪的敌人」？具体来说，是什么情况？",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501064,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501065,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "安杰丽卡",
            "CharImageID": 213,
            "Position": 1,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "StoryS05_045_03",
            "Words": "嘛……是穿着厚重铠甲的高大生物，自称为「克利姆索骑士」麻烦敌人呢。",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501065,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501066,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "杰西卡",
            "CharImageID": 22,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S08_030_02",
            "Words": "「克利姆索骑士」！？",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501066,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501067,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "杰西卡",
            "CharImageID": 22,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "StoryS05_045_03",
            "Words": "看来我的担忧要成为现实了……",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501067,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501068,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "安杰丽卡",
            "CharImageID": 213,
            "Position": 1,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S08_030_02",
            "Words": "啊哈？",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501068,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 501069,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "杰西卡",
            "CharImageID": 22,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "MainStory5S08_030_02",
            "Words": "安杰丽卡，请让铸剑者们一定要小心行事……",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          },
          {
            "ID": 501069,
            "Name": "第二部第2章战外后置",
            "NextDialogID": 0,
            "FrameType": 0,
            "PlaceName": "飞空艇工作舱",
            "CharName": "杰西卡",
            "CharImageID": 22,
            "Position": 0,
            "EnterType": 1,
            "BGM": "",
            "LeaveType": 0,
            "TogetherLeave": false,
            "LeaveTime": 0,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Background": "",
            "BackgroundImage": "Spine/Bg/7_ABS/BG76/BG76.png",
            "BackgroundX": 0,
            "Voice": "StoryS05_045_03",
            "Words": "150年前离开大陆的那把最初的邪剑……「真·阿鲁哈萨托」可能已经从月球之上归来了。",
            "BeforeEnterInsertEffect": 0,
            "BeforeTalkInsertEffect": 0,
            "AfterTalkInsertEffect": 0
          }
        ]
      }
    }
  }
</script>

