<template>
  <div>
    <div v-for="part in level">
      <div>({{part.Name}} {{part.PlaceName}}) {{part.CharName}}：{{part.Words}}</div>
    </div>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        level: [
          {
            "ID": 2002000,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 2002001,
            "FrameType": 0,
            "CharName": "艾梅达",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "魔族！？"
          },
          {
            "ID": 2002001,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 2002002,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "不对……这气息，并不是魔族的味道。"
          },
          {
            "ID": 2002002,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 2002003,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "你们、到底是什么人？"
          },
          {
            "ID": 2002003,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "吾等、名为「克利姆索骑士」……光是知晓这个名字就不应该放任由你们自由离开了。"
          },
          {
            "ID": 2002004,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "格尼尔",
            "CharImageID": 3,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_039_01",
            "Words": "什么……刚刚不是说他们不是魔物吗，居然有操纵魔物的能力！？"
          },
          {
            "ID": 2002005,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 2002006,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "鲁莽的人类、从吾等前进的道路上让开——我们的目标只有你们身后那颗世界之树。"
          },
          {
            "ID": 2002006,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 2002007,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "如果你们立刻投降的话，吾等还能放你们一条生路……"
          },
          {
            "ID": 2002007,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 2002008,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "世界之树！？见鬼，怎么可能让你们如愿！"
          },
          {
            "ID": 2002008,
            "Name": "第二部第2章-树的阴影、月的骑士-战前",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "看来你们的确是「那位大人」的敌人了，拔剑吧！"
          },
          {
            "ID": 2002009,
            "Name": "第二部第2章-树的阴影、月的骑士-战内",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "那么，立刻开始执行作战计划吧！"
          },
          {
            "ID": 2002010,
            "Name": "第二部第2章-树的阴影、月的骑士-战内",
            "NextDialogID": 2002011,
            "FrameType": 0,
            "CharName": "艾梅达",
            "CharImageID": 4,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "这些这些家伙的打扮……完全看不出是这个世界应该有的样子啊。"
          },
          {
            "ID": 2002011,
            "Name": "第二部第2章-树的阴影、月的骑士-战内",
            "NextDialogID": 2002012,
            "FrameType": 0,
            "CharName": "格尼尔",
            "CharImageID": 3,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_039_01",
            "Words": "和之前的陨星相关吗……难道是从月亮上来的家伙？"
          },
          {
            "ID": 2002012,
            "Name": "第二部第2章-树的阴影、月的骑士-战内",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "总之、这些所谓的克利姆索骑士想要对世界树不利，无论从什么立场来说——都是敌人没错了！"
          },
          {
            "ID": 2002013,
            "Name": "第二部第2章-树的阴影、月的骑士-战内-敌方",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "这几个人类实力不容小觑，而且他们的携带的那两把剑，非常不妙……是否要立刻返回禀告呢？"
          },
          {
            "ID": 2002014,
            "Name": "第二部第2章-树的阴影、月的骑士-战内-敌方",
            "NextDialogID": 2002015,
            "FrameType": 0,
            "CharName": "格尼尔",
            "CharImageID": 3,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_039_01",
            "Words": "还真看得起我们……现在想道要逃也太晚了吧！"
          },
          {
            "ID": 2002015,
            "Name": "第二部第2章-树的阴影、月的骑士-战内-敌方",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "艾梅达",
            "CharImageID": 4,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "笨蛋，他们惧怕的……是兰古利萨和阿鲁哈萨托的力量！"
          },
          {
            "ID": 2002016,
            "Name": "第二部第2章-树的阴影、月的骑士-战后",
            "NextDialogID": 2002017,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "没想到……竟然输给了人类……"
          },
          {
            "ID": 2002017,
            "Name": "第二部第2章-树的阴影、月的骑士-战后",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "没能完成……摧毁这颗世界树的计划……"
          },
          {
            "ID": 2002018,
            "Name": "第二部第2章-树的阴影、月的骑士-战后",
            "NextDialogID": 2002019,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "这些家伙、既不是「魔族」也不是「人类」吗……我有一种不祥的预感……"
          },
          {
            "ID": 2002019,
            "Name": "第二部第2章-树的阴影、月的骑士-战后",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "可恶，必须尽快找到陨星的坠落点了！"
          },
          {
            "ID": 2201000,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 2201001,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "不……还不能在这里倒下，一定要把这个信息回报给那位大人……"
          },
          {
            "ID": 2201001,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "人类……已经重新铸造了兰古利萨和阿鲁哈萨托……"
          },
          {
            "ID": 2201002,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 2201003,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "多留了个心眼果然是正确的吗……受了这么重的伤，竟然还没有放弃。"
          },
          {
            "ID": 2201003,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 2201004,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "从某种意义上来说也算是值得尊敬的对手了。"
          },
          {
            "ID": 2201004,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "说吧……袭击世界树并与我们为敌，到底是为了什么！？"
          },
          {
            "ID": 2201005,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "一切……都为了雷因法鲁斯大人崇高的计划——！！！"
          },
          {
            "ID": 2201006,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 2201007,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "！？！？"
          },
          {
            "ID": 2201007,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 2201008,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "召唤魔法……！？不对、这是……"
          },
          {
            "ID": 2201008,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战前",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "世界树的记忆之力！？"
          },
          {
            "ID": 2201009,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战内",
            "NextDialogID": 2201010,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "见鬼，世界树的记忆之力、这次是站在他们那一边的吗！？"
          },
          {
            "ID": 2201010,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战内",
            "NextDialogID": 2201011,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "吾等……是克利姆索尼亚一族的骄傲，一骑当千的不屈战士！"
          },
          {
            "ID": 2201011,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战内",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "为了种族的延续，吾等……将不惜一切代价完成使命！"
          },
          {
            "ID": 2201012,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后",
            "NextDialogID": 2201013,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "力量……消散了……"
          },
          {
            "ID": 2201013,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "唔，看来世界树的力量不总是向着我们这边的啊……今后的旅程要多加小心了。"
          },
          {
            "ID": 2201014,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "…………"
          },
          {
            "ID": 2201015,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "这是……世界树关于克利姆索骑士，真正的记忆吗？"
          },
          {
            "ID": 2201016,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "克利姆索骑士团，已整备完毕！王子殿下，请检阅！"
          },
          {
            "ID": 2201017,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201018,
            "FrameType": 0,
            "CharName": "雷因法鲁斯",
            "CharImageID": 63,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "辛苦了……"
          },
          {
            "ID": 2201018,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201019,
            "FrameType": 0,
            "CharName": "雷因法鲁斯",
            "CharImageID": 63,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "我们已经在黑暗无光的故乡里沉眠了两百年了，永恒的沉睡让我的身与心都如同这无情的宇宙一样的寒冷。"
          },
          {
            "ID": 2201019,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "雷因法鲁斯",
            "CharImageID": 63,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "而如今，就连维持永眠装置的能量都已经竭尽枯竭，我们必须来到这卑微的地上来获取继续苟全性命的能量……"
          },
          {
            "ID": 2201020,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201021,
            "FrameType": 0,
            "CharName": "雷因法鲁斯",
            "CharImageID": 63,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "但是，我们从来没有忘记过这个事实……"
          },
          {
            "ID": 2201021,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201022,
            "FrameType": 0,
            "CharName": "雷因法鲁斯",
            "CharImageID": 63,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "我们克里木索尼亚曾经是这个世界的王者！我们从来没有放弃对过去荣耀的渴望！"
          },
          {
            "ID": 2201022,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201023,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "王者必将归来！"
          },
          {
            "ID": 2201023,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201024,
            "FrameType": 0,
            "CharName": "雷因法鲁斯",
            "CharImageID": 63,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "这是我们唯一一个也是最后一个机会，拯救我们濒死边缘种族的最后一个机会！"
          },
          {
            "ID": 2201024,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201025,
            "FrameType": 0,
            "CharName": "雷因法鲁斯",
            "CharImageID": 63,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "为此花费了两百年时间种植世界树，为了让这个星球充满能传输到我们故乡的魔法能量！"
          },
          {
            "ID": 2201025,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201026,
            "FrameType": 0,
            "CharName": "雷因法鲁斯",
            "CharImageID": 63,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "在完成这个计划之前，杀戮……不会终止！为了完成这个计划，我会不惜一切代价！"
          },
          {
            "ID": 2201026,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "克利姆索骑士",
            "CharImageID": 4,
            "Position": 1,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_038_02",
            "Words": "为了雷因法鲁斯大人！不惜一切代价！"
          },
          {
            "ID": 2201027,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201028,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "……这是，克利姆索骑士……过去的记忆吗？"
          },
          {
            "ID": 2201028,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 2201029,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "雷因法鲁斯、红月「克利姆索」上的危机……"
          },
          {
            "ID": 2201029,
            "Name": "第二部第2章-断章故事1-1：克利姆索骑士-战后演出",
            "NextDialogID": 0,
            "FrameType": 0,
            "CharName": "马修",
            "CharImageID": 1,
            "Position": 0,
            "EnterType": 1,
            "PreAnimation": "",
            "PreFacialAnimation": "",
            "IdleAnimation": "idle_Dialog_Normal",
            "IdleFacialAnimation": "idle_Dialog_Normal",
            "Voice": "MainStory5S18_037_05",
            "Words": "这份记忆，我收下了……"
          }
        ]
      }
    }
  }
</script>

